---
kind: pipeline
type: docker
name: default

clone:
  depth: 1

steps:
- name: firststep 
  image: python:3.8
  commands:
    - echo "dummy step for drone DAG"

- name: pycodestyle
  image: python:3.8
  depends_on: [firststep]
  commands:
    - pip install pycodestyle
    - pycodestyle --ignore=E501,W503 ./

- name: black
  image: python:3.8
  depends_on: [firststep]
  commands:
    - pip install black
    - black --check ./

- name: safety
  image: python:3.8
  depends_on: [firststep]
  commands:
    - pip install safety
    - safety check

- name: backend
  image: kkarolis/cct-subsilocus
  depends_on: [firststep]
  environment:
    POSTGRES_DB: subsilocus
    POSTGRES_USER: subsilocus
    POSTGRES_PASSWORD: subsilocus
    POSTGRES_HOST: db
    POSTGRES_PORT: 5432
    SECRET_KEY: TEST_KEY
    DEBUG: true
  commands:
    # switch the built-in version with the new one
    - rm -rf /var/lib/appuser/app/*
    - cp -r $PWD/* /var/lib/appuser/app
    - cd /var/lib/appuser/app
    - entrypoint test

services:
  - name: db
    image: postgres:10
    environment:
      POSTGRES_DB: subsilocus
      POSTGRES_USER: subsilocus
      POSTGRES_PASSWORD: subsilocus
