version: '3'

services:
  subsilocus:
    build: 
      context: .
    environment:
      # SECURITY WARNING: only for development version
      - SECRET_KEY=NOT_VERY_SECRET
      - DEBUG=true
    volumes:
      - './:/var/lib/appuser/app'
