# Generated by Django 3.0.3 on 2020-02-07 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("datetime_from", models.DateTimeField()),
                ("datetime_to", models.DateTimeField()),
                (
                    "meeting_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reservations.MeetingRoom",
                    ),
                ),
            ],
            options={"ordering": ["id"]},
        ),
    ]
