# Generated by Django 3.0.3 on 2020-02-07 10:25

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_auto_20200207_1016"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reservation", name="datetime_to_gt_from",
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                check=models.Q(
                    datetime_to__gt=django.db.models.expressions.F("datetime_from")
                ),
                name="datetime_to_gt_from",
            ),
        ),
    ]
