# Generated by Django 3.0.3 on 2020-02-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0005_auto_20200208_0645"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
